package engine;

public enum DimensionNameSet implements DimensionName{
	//INITIAL SET OF DIMENSION NAMES AT COMPILE TIME
	
	OFF,
	ON,
	TYPE_CELL,
	TYPE_3,
	TYPE_CELL_SPACE_RELATION,
	TYPE_CELL_TIME_RELATION,
	TYPE_5,
	TYPE_OBJECT_MEMBERSHIP_RELATION,
	ROLE_CELL_NEIGHBOR,
	ROLE_CELL_SOURCE,
	ROLE_CELL_TARGET,
	ROLE_5_0,
	ROLE_5_1,
	ROLE_CONTAINER,
	ROLE_MEMBER,
	HASCHILD_TYPE_3,
	HASCHILD_TYPE_5,
	SIZE,
	LIFETIME

}
